### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by laizy** [goshennetwork/rollup-contracts#43]
- [x] 修复decodeMMRFromRlpHeader，现在mmr root和size改成了header 的nonce和mixHash字段。
- [x] 同步L1的Bridge/witness合约数据；
- [x] 同步L2的Bridge/witness合约数据；
- [x] go-ethereum增加一个layer2模块的rpc服务，提供相关数据的查询；
- [ ] rollupcli完善l1和l2的gateway；
- [x] 获取每个区块执行时读取的存储状态数据(trie的存储数据proof和合约code)；
